const concat = require('concat');
try {

    concat(['/Users/mac/Documents/IPTV/Isarel.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Isarel.m3u8')
    concat(['/Users/mac/Documents/IPTV/news.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal news.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Algeria.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Algeria.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Arab_News.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Arab_News.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Bahrain.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Bahrain.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Egypt.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Egypt.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Iran.m3u'], '/Users/mac/Documents/IPTV/Output/Normal Iran.m3u')
    concat(['/Users/mac/Documents/IPTV/Arab/Iraq.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Iraq.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Jordan.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Jordan.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Kuwait.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Kuwait.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Lebanon.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Lebanon.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Libya.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Libya.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Morooco.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Morooco.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Qatar.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Qatar.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Saudi.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Saudi.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Syria.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Syria.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Tunisia.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Tunisia.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Turkey.m3u'], '/Users/mac/Documents/IPTV/Output/Normal Turkey.m3u')
    concat(['/Users/mac/Documents/IPTV/Arab/UAE.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal UAE.m3u8')
    concat(['/Users/mac/Documents/IPTV/Arab/Yemen.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Yemen.m3u8')
    concat(['/Users/mac/Documents/IPTV/Entertainment/Fashion.m3u8', '/Users/mac/Documents/IPTV/Entertainment/Learning.m3u8', '/Users/mac/Documents/IPTV/Entertainment/Music_Radio.m3u8', '/Users/mac/Documents/IPTV/Entertainment/VOD.m3u8', '/Users/mac/Documents/IPTV/Entertainment/entertainment.m3u', '/Users/mac/Documents/IPTV/Entertainment/kids.m3u8', '/Users/mac/Documents/IPTV/Entertainment/movie.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Entertainment.m3u8')
    concat(['/Users/mac/Documents/IPTV/Asia/Indonesia.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Indonesia.m3u8')
    concat(['/Users/mac/Documents/IPTV/Asia/Japan.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Japan.m3u8')
    concat(['/Users/mac/Documents/IPTV/Asia/Korea.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Korea.m3u8')
    concat(['/Users/mac/Documents/IPTV/Asia/Singapore.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Singapore.m3u8')
    concat(['/Users/mac/Documents/IPTV/Asia/Thailand.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Thailand.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Demark.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Demark.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/France.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal France.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Germany.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Germany.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Italy.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Italy.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Kosovo.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Kosovo.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Malta.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Malta.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Russia.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Russia.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/Spain.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Spain.m3u8')
    concat(['/Users/mac/Documents/IPTV/Europe/uk.M3U8'], '/Users/mac/Documents/IPTV/Output/Normal uk.M3U8')
    concat(['/Users/mac/Documents/IPTV/India/Assamese.m3u8', '/Users/mac/Documents/IPTV/India/Bangla.m3u8', '/Users/mac/Documents/IPTV/India/Bhojpuri.m3u8', '/Users/mac/Documents/IPTV/India/English.m3u8', '/Users/mac/Documents/IPTV/India/Gujarat.m3u8', '/Users/mac/Documents/IPTV/India/Hindi.m3u8', '/Users/mac/Documents/IPTV/India/Kannada.m3u8', '/Users/mac/Documents/IPTV/India/Malayalam.m3u8', '/Users/mac/Documents/IPTV/India/Marathi.m3u8', '/Users/mac/Documents/IPTV/India/Oriya.m3u8', '/Users/mac/Documents/IPTV/India/Punjabi.m3u8', '/Users/mac/Documents/IPTV/India/Rajasthan.m3u8', '/Users/mac/Documents/IPTV/India/Tamil.m3u8', '/Users/mac/Documents/IPTV/India/Telugu.m3u8', '/Users/mac/Documents/IPTV/India/Urdu.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal India.m3u8')
    concat(['/Users/mac/Documents/IPTV/Latin_America/Latino.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Latino.m3u8')
    concat(['/Users/mac/Documents/IPTV/North_America/Canada.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Canada.m3u8')
    concat(['/Users/mac/Documents/IPTV/North_America/USA.m3u8', '/Users/mac/Documents/IPTV/North_America/USA_Regional_TV.m3u8', '/Users/mac/Documents/IPTV/North_America/US_gov_access_tv.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal North_America.m3u8')
    concat(['/Users/mac/Documents/IPTV/Sports/Baseball.m3u8', '/Users/mac/Documents/IPTV/Sports/Bein_Sports.m3u8', '/Users/mac/Documents/IPTV/Sports/Eleven.m3u8', '/Users/mac/Documents/IPTV/Sports/Football.m3u8', '/Users/mac/Documents/IPTV/Sports/Fox.m3u8', '/Users/mac/Documents/IPTV/Sports/France.m3u8', '/Users/mac/Documents/IPTV/Sports/Sky_Sports.m3u8', '/Users/mac/Documents/IPTV/Sports/Sports.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Sports.m3u8')
    concat(['/Users/mac/Documents/IPTV/Asia/Chinese/China.m3u8', '/Users/mac/Documents/IPTV/Asia/Chinese/Chinese_News.m3u8', '/Users/mac/Documents/IPTV/Asia/Chinese/Chinese_Regional.m3u8', '/Users/mac/Documents/IPTV/Asia/Chinese/HongKong.m3u8', '/Users/mac/Documents/IPTV/Asia/Chinese/Taiwan.m3u8'], '/Users/mac/Documents/IPTV/Output/Normal Chinese.m3u8')

} catch(e) {
    console.log('error', e)
}
